name: First workflow
on: [push]

jobs:
  runs-shell-commands:
    runs-on: ubuntu-latest
    steps:
    -  name: echo a string
       run: echo "Hello work"
    -  name:  Execute multiple commands
       run: |
        node -v
        npm -v
